### ISSUE TITLE
1.10.2

### ISSUE THREAD

**Issue by marcin212** [marcin212/Zetta-Industries#45]
java.lang.NullPointerException: Unexpected error
    at com.bymarcin.zettaindustries.mods.battery.erogenousbeef.core.multiblock.MultiblockControllerBase.selectNewReferenceCoord(MultiblockControllerBase.java:853)
    at com.bymarcin.zettaindustries.mods.battery.erogenousbeef.core.multiblock.MultiblockControllerBase.detachBlock(MultiblockControllerBase.java:239)
    at com.bymarcin.zettaindustries.mods.battery.erogenousbeef.core.multiblock.MultiblockTileEntityBase.detachSelf(MultiblockTileEntityBase.java:353)
    at com.bymarcin.zettaindustries.mods.battery.erogenousbeef.core.multiblock.MultiblockTileEntityBase.onChunkUnload(MultiblockTileEntityBase.java:142)
    at net.minecraft.world.World.func_72939_s(World.java:1841)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1789)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Acerixx** [comment]
java.lang.NullPointerException: Unexpected error
    at com.bymarcin.zettaindustries.mods.battery.erogenousbeef.core.multiblock.MultiblockTileEntityBase.getNeighboringParts(MultiblockTileEntityBase.java:317)
    at com.bymarcin.zettaindustries.mods.battery.erogenousbeef.core.multiblock.MultiblockTileEntityBase.attachToNeighbors(MultiblockTileEntityBase.java:48)
    at com.bymarcin.zettaindustries.mods.battery.erogenousbeef.core.multiblock.MultiblockWorldRegistry.processMultiblockChanges(MultiblockWorldRegistry.java:132)
    at com.bymarcin.zettaindustries.mods.battery.erogenousbeef.core.multiblock.MultiblockRegistry.tickStart(MultiblockRegistry.java:25)
    at com.bymarcin.zettaindustries.mods.battery.erogenousbeef.core.multiblock.MultiblockClientTickHandler.onClientTick(MultiblockClientTickHandler.java:12)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_492_MultiblockClientTickHandler_onClientTick_ClientTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:339)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1650)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
