### ISSUE TITLE
Client crash when respawning after death

### ISSUE THREAD

**Issue by citpo** [marcin212/Zetta-Industries#50]
Getting the following stacktrance pointing to RF Meter
Using version: zettaindustries-1.2-1.10.2-130
Added to Direwolf20 1.10.2 pack  version 1.4.1
```
Time: 1/19/17 8:10 PM
Description: Rendering Block Entity

java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=front, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:196)
	at com.bymarcin.zettaindustries.mods.rfpowermeter.render.RFMeterRender.renderTileEntityFast(RFMeterRender.java:75)
	at com.bymarcin.zettaindustries.mods.rfpowermeter.render.RFMeterRender.renderTileEntityFast(RFMeterRender.java:37)
	at net.minecraftforge.client.model.animation.FastTESR.func_180535_a(FastTESR.java:58)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:147)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:125)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:701)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1315)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1038)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Time: 1/19/17 8:10 PM
Description: Rendering Block Entity

java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=front, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:196)
	at com.bymarcin.zettaindustries.mods.rfpowermeter.render.RFMeterRender.renderTileEntityFast(RFMeterRender.java:75)
	at com.bymarcin.zettaindustries.mods.rfpowermeter.render.RFMeterRender.renderTileEntityFast(RFMeterRender.java:37)
	at net.minecraftforge.client.model.animation.FastTESR.func_180535_a(FastTESR.java:58)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:147)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:125)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:701)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1315)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1038)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by marcin212** [comment]
fixed, new version: https://ci.bymarcin.com/job/Zetta-Industries/lastSuccessfulBuild/artifact/build/libs/zettaindustries-1.2-1.10.2-131.jar
